### ISSUE TITLE
Incompatibility with 1.21.4+

### ISSUE THREAD

**Issue by leeineian** [wyatt-herkamp/too-many-shortcuts#18]
Take your time.

**Comment by wyatt-herkamp** [comment]
Expect this to be done on Wednesday.

**Comment by leeineian** [comment]
Okay! While you're at it, I noticed the "Keybinds" text beside the search bar is noticeably smaller than it should be, it's also positioned upwards instead of the center (take a look at the "Controls" title for example).

**Comment by wyatt-herkamp** [comment]
Update

I had a family emergency happen and kind of forgot about this. Will try to update this tomorrow.

**Comment by wyatt-herkamp** [comment]
Been released. https://modrinth.com/mod/too-many-shortcuts
