### ISSUE TITLE
A flaw in the update "0.0.2+mc.1.21".

### ISSUE THREAD

**Issue by CtrelokCvobods** [wyatt-herkamp/too-many-shortcuts#9]
After the update "0.0.2+mc.1.21" "Escape" + selecting the key leads to exiting the menu, which does not allow you to conveniently remove the assignment from the key.

**Comment by wyatt-herkamp** [comment]
https://github.com/wyatt-herkamp/too-many-shortcuts/actions/runs/9810251335

Try against the latest build. I think it is corrected. You will need to extract the jar from the zip file. It is located in `build/libs/`

**Comment by CtrelokCvobods** [comment]
Yes, it has been fixed.
